<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>API检查</AssemblyName>
    <RootNamespace>PvzApiCheck</RootNamespace>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Mono.Cecil">
      <HintPath>$(MSBuildThisFileDirectory)..\..\工具\Mono.Cecil.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
